# --- General options --- #
url: "http://obiorag.github.io"
baseurl: ""

# Name of website
title: General Ozochiawaeze's Home Page
description: Welcome to General Ozochiawaeze's Homepage! 

# --- Navigation bar options --- #
navbar-links:
  About Me: "about"
  Research: "research"
  Experiences: "experiences"

# Image to show in the navigation bar
avatar: "/img/mypicbirs.jpg"

# --- Footer options --- #
author:
  name: General Ozochiawaeze
  email: "oozochia@purdue.edu"
  github: obiorag

footer-links-active:
  linkedin: true   # Enable LinkedIn in footer
  github: true     # Enable GitHub in footer
  email: true      # Enable Email in footer
  twitter: false   # Disable Twitter in footer
  instagram: true  # Enable Instagram in footer
  rss: true        # Enable RSS feed in footer (if desired)

share-links-active:
  twitter: false   # Disable Twitter share links
  facebook: false  # Disable Facebook share links
  google: false    # Disable Google share links
  linkedin: true   # Enable LinkedIn share links

# --- Misc --- #
# If you want to use Google Analytics for tracking, enter your Google Analytics ID here.
google_analytics: "UA-109004213-1"   # Add your own tracking ID if you wish

# Excerpt Word Length
excerpt_length: 20

# Character used to separate site title and description in HTML document title
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #
timezone: "America/EST"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 100

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: ""  # Applies to all files
    values:
      layout: "page"
      show-avatar: true

# Add custom CSS file if needed (make sure it’s in the correct folder)
assets:
  - /assets/css/style.css
